services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    volumes:
      - beszel_data:/beszel_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.martin-linde.com`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.routers.beszel.tls.certresolver=letsencrypt"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel_agent_data:/var/lib/beszel-agent
    environment:
      PORT: 45876
      KEY: ${KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel-agent.rule=Host(`nuc.martin-linde.com`) && PathPrefix(`/agent`)"
      - "traefik.http.routers.beszel-agent.entrypoints=websecure"
      - "traefik.http.routers.beszel-agent.tls=true"
      - "traefik.http.routers.beszel-agent.tls.certresolver=letsencrypt"
      - "traefik.http.services.beszel-agent.loadbalancer.server.port=45876"

volumes:
  beszel_data:
  beszel_agent_data:
